/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.KlijentController;
import domain.Drzavljanstvo;
import domain.Pacijent;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author korisnk
 */
public class FormaNoviPacijent extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaNoviPacijent.class.getName());

    /**
     * Creates new form FormaNoviGost
     */
    public FormaNoviPacijent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Unos novog pacijenta");
        setLocationRelativeTo(parent);
        jButtonIzmeniPacijenta.setVisible(false);
       // jButtonZatvori.addActionListener(e -> dispose());
        jButtonDodajPacijenta.addActionListener(e -> sacuvajPacijenta());
        jButtonObrisiPacijenta.setVisible(false);
        jButtonObrisiPacijenta.setEnabled(false);
        popuniDrzavljanstva();
       }

    
    int hiddenIdPacijent = 0;

    public FormaNoviPacijent(java.awt.Frame parent, boolean modal, domain.Pacijent selektovan) {
        super(parent, modal);       
        initComponents();
        setTitle("Detalji pacijenta");
        setLocationRelativeTo(parent);

        jButtonDodajPacijenta.setVisible(false);
        jButtonDodajPacijenta.setEnabled(false);
        jButtonIzmeniPacijenta.setVisible(true);
        jButtonIzmeniPacijenta.setEnabled(true);

        jButtonObrisiPacijenta.setVisible(true);
        jButtonObrisiPacijenta.setEnabled(true);

        popuniDrzavljanstva();
        if(selektovan!=null){
            hiddenIdPacijent = selektovan.getIdPacijent();
            jTextFieldIme.setText(selektovan.getIme());
            jTextFieldPrezime.setText(selektovan.getPrezime());
            jTextFieldEmail.setText(selektovan.getEmail());
        }
        if(selektovan==null) return;
        int idDrz = (selektovan.getDrzavljanstvo() != null) ? selektovan.getDrzavljanstvo().getIdDrzavljanstvo() : -1;
        for (int i = 0; i < jComboBoxDrzavljanstvo.getItemCount(); i++) {
            Drzavljanstvo d = jComboBoxDrzavljanstvo.getItemAt(i);
            if (d != null && d.getIdDrzavljanstvo() == idDrz) {
                jComboBoxDrzavljanstvo.setSelectedIndex(i);
                break;
            }

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonZatvori = new javax.swing.JButton();
        jButtonDodajPacijenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDrzavljanstvo = new javax.swing.JComboBox<>();
        jButtonIzmeniPacijenta = new javax.swing.JButton();
        jButtonObrisiPacijenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ime:");

        jLabel2.setText("prezime:");

        jLabel3.setText("email:");

        jButtonZatvori.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonZatvori.setText("zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        jButtonDodajPacijenta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonDodajPacijenta.setText("dodaj pacijenta");
        jButtonDodajPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPacijentaActionPerformed(evt);
            }
        });

        jLabel5.setText("državljanstvo:");

        jButtonIzmeniPacijenta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonIzmeniPacijenta.setText("izmeni pacijenta");
        jButtonIzmeniPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniPacijentaActionPerformed(evt);
            }
        });

        jButtonObrisiPacijenta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonObrisiPacijenta.setText("obriši pacijenta");
        jButtonObrisiPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiPacijentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIme))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldPrezime))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jComboBoxDrzavljanstvo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonObrisiPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonIzmeniPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonDodajPacijenta, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDrzavljanstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDodajPacijenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisiPacijenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIzmeniPacijenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jButtonZatvori)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonIzmeniPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniPacijentaActionPerformed
            try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || drz == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
                return;
            }
            if (!email.contains("@")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Neispravan e-mail.");
                return;
            }
            
            domain.Pacijent izmenjen = new domain.Pacijent(hiddenIdPacijent, ime, prezime, email, drz);
            controller.KlijentController.getInstance().updatePacijent(izmenjen);

            javax.swing.JOptionPane.showMessageDialog(this, "Sistem je zapamtio pacijenta.");
            this.dispose();  
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti pacijenta.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIzmeniPacijentaActionPerformed

    private void jButtonObrisiPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiPacijentaActionPerformed
        
        if (hiddenIdPacijent <= 0) {
            JOptionPane.showMessageDialog(this, "Nema vazeceg ID-ja pacijenta za brisanje.");
            return;
        }

        int potvrda = JOptionPane.showConfirmDialog(
                this,
                "Obrisati ovog pacijenta?",
                "Potvrda",
                JOptionPane.YES_NO_OPTION
        );
        if (potvrda != JOptionPane.YES_OPTION) return;

        try {
            Pacijent p = new Pacijent();
            p.setIdPacijent(hiddenIdPacijent);    
            KlijentController.getInstance().deletePacijent(p);
            JOptionPane.showMessageDialog(this, "Sistem je obrisao pacijenta.");
            dispose();                      // zatvori dijalog
        } catch (java.sql.SQLIntegrityConstraintViolationException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Pacijent ne moze da se obrise jer postoje povezani racuni.",
                "Greska",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Sistem ne moze da obrise pacijenta.",
                "Greska",
                JOptionPane.ERROR_MESSAGE
            );
        }



    }//GEN-LAST:event_jButtonObrisiPacijentaActionPerformed

    private void jButtonDodajPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPacijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDodajPacijentaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajPacijenta;
    private javax.swing.JButton jButtonIzmeniPacijenta;
    private javax.swing.JButton jButtonObrisiPacijenta;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JComboBox<Drzavljanstvo> jComboBoxDrzavljanstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void sacuvajPacijenta() {
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || drz == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
                return;
            }
            if (!email.contains("@")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Neispravan e-mail.");
                return;
            }

            domain.Pacijent p = new domain.Pacijent(0, ime, prezime, email, drz);
            KlijentController.getInstance().addPacijent(p);

            javax.swing.JOptionPane.showMessageDialog(this, "Sistem je zapamtio pacijenta.");
            dispose();
        
    } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti pacijenta.","Greska", JOptionPane.ERROR_MESSAGE);
    }
    }

    private void popuniDrzavljanstva() {
         try {
             ArrayList<domain.Drzavljanstvo> lista =
                   KlijentController.getInstance().getAllDrzavljanstvo();
            jComboBoxDrzavljanstvo.removeAllItems();
            for (domain.Drzavljanstvo d : lista) {
                jComboBoxDrzavljanstvo.addItem(d);
            }
    } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Greska pri ucitavanju drzavljanstava: " + ex.getMessage());
    }
    }
}
