/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.KlijentController;
import domain.Pacijent;
import domain.Racun;
import domain.Lekar;
import domain.VrstaMedUsluge;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modeli.TableModelStavkeRacuna;

/**
 *
 * @author korisnk
 */
public class FormaDetaljiRacuna extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaDetaljiRacuna.class.getName());
    private final Racun racun;

    /**
     * Creates new form FormaDetaljiRacun
     */
    public FormaDetaljiRacuna(java.awt.Frame parent, boolean modal, Racun racun) {
        super(parent, modal);
        initComponents();
       // jButtonIzmeni.addActionListener(e -> jButtonIzmeniActionPerformed());
        popuniUsluge();

        setTitle("Izmeni racun");
        this.racun = racun;
        
        TableModelStavkeRacuna model = new TableModelStavkeRacuna(racun);
        jTableStavkeRacuna.setModel(model);
        int id = racun.getIdRacuna();
        Date datum = racun.getDatumIzdavanja();
        Lekar l = racun.getLekar();
        Pacijent p = racun.getPacijent();
        
        jLabelIDRacuna.setText(id+"");
        jLabelIDRacuna.setEnabled(false);
        
        jTextFieldLekar.setText(l.getIme()+ " "+l.getPrezime());
        jTextFieldLekar.setEnabled(false);
        
        jTextFieldPacijent.setText(p.getIme() + " " + p.getPrezime());
        jTextFieldPacijent.setEnabled(false);
        
        jTextFieldDatumIzdavanja.setText(datum+"");
        jTextFieldDatumIzdavanja.setEnabled(false);
        
        jTextFieldCena.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeRacuna = new javax.swing.JTable();
        jButtonZatvori = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jLabelIDRacuna = new javax.swing.JLabel();
        jTextFieldDatumIzdavanja = new javax.swing.JTextField();
        jTextFieldLekar = new javax.swing.JTextField();
        jTextFieldPacijent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxVrstaUsluge = new javax.swing.JComboBox<>();
        jTextFieldKolicina = new javax.swing.JTextField();
        jTextFieldCena = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID racuna:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 103, -1));

        jLabel3.setText("Datum izdavanja:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 31, 103, -1));

        jLabel4.setText("Lekar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 62, 103, -1));

        jLabel5.setText("Pacijent:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 103, -1));

        jTableStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeRacuna);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 138, -1, 119));

        jButtonZatvori.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonZatvori.setText("zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonZatvori, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 263, 86, -1));

        jButtonIzmeni.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonIzmeni.setText("izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 221, 90, -1));
        getContentPane().add(jLabelIDRacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 6, 78, 16));
        getContentPane().add(jTextFieldDatumIzdavanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 28, 201, -1));
        getContentPane().add(jTextFieldLekar, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 56, 201, -1));
        getContentPane().add(jTextFieldPacijent, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 84, 201, -1));

        jLabel1.setText("Vrsta usluge:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 26, 92, -1));

        jLabel6.setText("Kolicina:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 54, 92, -1));

        jLabel7.setText("Cena:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 79, 92, -1));

        jComboBoxVrstaUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVrstaUslugeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxVrstaUsluge, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 23, 201, -1));
        getContentPane().add(jTextFieldKolicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 51, 201, -1));
        getContentPane().add(jTextFieldCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 82, 201, -1));

        jButtonDodaj.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonDodaj.setText("dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDodaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 79, -1, -1));

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButtonObrisi.setText("obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 186, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
         
        this.dispose();  
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
          try {
            if (jTableStavkeRacuna.isEditing()) {
                jTableStavkeRacuna.getCellEditor().stopCellEditing();
            }

            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavkeRacuna.getModel();

            double ukupno = 0.0;
            for (domain.StavkaRacuna s : tm.getStavke()) {
                ukupno += s.getIznos();
            }

            racun.setStavke(new ArrayList<>(tm.getStavke()));
            racun.setUkupniIznos(ukupno);

            KlijentController.getInstance().updateRacun(racun);

            javax.swing.JOptionPane.showMessageDialog(this, "Racun je uspesno izmenjen.");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Sistem ne moze da zapamti racun.",
                "Greska",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        try {
            domain.VrstaMedUsluge vu = (domain.VrstaMedUsluge) jComboBoxVrstaUsluge.getSelectedItem();
            if (vu == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi vrstu usluge.");
                return;
            }

            String kolicinaString = jTextFieldKolicina.getText().trim();
            if (kolicinaString.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Unesi kolicinu.");
                return;
            }
            int kolicina = Integer.parseInt(kolicinaString);
            if (kolicina <= 0) {
                JOptionPane.showMessageDialog(this, "Kolicina mora biti veća od 0.");
                return;
            }

            double cena;
            String cenaTxt = jTextFieldCena.getText().trim().replace(',', '.');
            if (cenaTxt.isEmpty()) {
                cena = vu.getCena();
            } else {
                cena = Double.parseDouble(cenaTxt);
                if (cena < 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Cena ne moze biti negativna.");
                    return;
                }
            }

            double iznos = cena * kolicina;

            domain.StavkaRacuna sr = new domain.StavkaRacuna();
            sr.setIdRacuna(racun.getIdRacuna()); 
            sr.setVrstaMedUsluge(vu);
            sr.setKolicina(kolicina);
            sr.setCenaUsluge(cena);
            sr.setIznos(iznos);

            modeli.TableModelStavkeRacuna tm = (modeli.TableModelStavkeRacuna) jTableStavkeRacuna.getModel();
            tm.dodajStavku(sr);

            jTextFieldKolicina.setText("");
            jTextFieldCena.setText(String.valueOf(vu.getCena()));

        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Neispravan broj (kolicina/cena).");
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
            int viewRow = jTableStavkeRacuna.getSelectedRow();
            if (viewRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Izaberi stavku iz tabele!");
                return;
            }
            int modelRow = jTableStavkeRacuna.convertRowIndexToModel(viewRow);
            ((modeli.TableModelStavkeRacuna) jTableStavkeRacuna.getModel()).obrisiStavku(modelRow);
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jComboBoxVrstaUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVrstaUslugeActionPerformed
        domain.VrstaMedUsluge vu = (domain.VrstaMedUsluge) jComboBoxVrstaUsluge.getSelectedItem();
        if (vu != null) {
             jTextFieldCena.setText(String.valueOf(vu.getCena()));
        } else {
            jTextFieldCena.setText("");
        }       
    }//GEN-LAST:event_jComboBoxVrstaUslugeActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JComboBox<VrstaMedUsluge> jComboBoxVrstaUsluge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelIDRacuna;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkeRacuna;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldDatumIzdavanja;
    private javax.swing.JTextField jTextFieldKolicina;
    private javax.swing.JTextField jTextFieldLekar;
    private javax.swing.JTextField jTextFieldPacijent;
    // End of variables declaration//GEN-END:variables

    private void jButtonIzmeniActionPerformed() {
         try {
        if (jTableStavkeRacuna.isEditing()) {
            jTableStavkeRacuna.getCellEditor().stopCellEditing();
        }

        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavkeRacuna.getModel();

        double ukupno = 0.0;
        for (domain.StavkaRacuna s : tm.getStavke()) {
            ukupno += s.getIznos();
        }

        racun.setStavke(new java.util.ArrayList<>(tm.getStavke()));
        racun.setUkupniIznos(ukupno);

        
              KlijentController.getInstance().updateRacun(racun);

             // JOptionPane.showMessageDialog(this, "Racun je uspesno izmenjen.");
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Sistem ne moze da zapamti racun.",
                "Greska", JOptionPane.ERROR_MESSAGE);
    }

    }

    private void popuniUsluge() {
         try {
             ArrayList<domain.VrstaMedUsluge> usluge =
                controller.KlijentController.getInstance().getAllVrstaUsluge();
        jComboBoxVrstaUsluge.removeAllItems();
        for (domain.VrstaMedUsluge v : usluge) {
            jComboBoxVrstaUsluge.addItem(v); 
        }
        VrstaMedUsluge usluga = (domain.VrstaMedUsluge) jComboBoxVrstaUsluge.getSelectedItem();
        if (usluga != null) jTextFieldCena.setText(String.valueOf(usluga.getCena()));
    } catch (Exception ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Ne mogu da ucitam usluge.");
    }
    }

   private double izracunajUkupno() {
        modeli.TableModelStavkeRacuna tm = (modeli.TableModelStavkeRacuna) jTableStavkeRacuna.getModel();
        double total = 0;
        for (domain.StavkaRacuna s : tm.getStavke()) total += s.getIznos();
        return total;
        }
}
