/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.KlijentController;
import domain.Pacijent;
import javax.swing.JOptionPane;
import modeli.TableModelPacijent;
import domain.Drzavljanstvo;
import java.util.ArrayList;

/**
 *
 * @author korisnk
 */
public class FormaPretraziPacijent extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaPretraziPacijent.class.getName());

    /**
     * Creates new form FormaPretraziGost
     */
    private TableModelPacijent model;
    public FormaPretraziPacijent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Pretrazi pacijenta");
        initComponents();
        model = new TableModelPacijent();
        jTablePacijenti.setModel(model);
        //jButtonpretraziGosta.addActionListener(e -> pretrazi());
       // jButtonObrisiGosta.addActionListener(e -> obrisiSelektovanog());
       // jButtonDetaljiGosta.addActionListener(e -> izmeniSelektovanog());

        popuniDrzavljanstva();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacijenti = new javax.swing.JTable();
        jButtonPretraziPacijenta = new javax.swing.JButton();
        jButtonDetaljiPacijenta = new javax.swing.JButton();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDrzavljanstvo = new javax.swing.JComboBox<>();
        jButtonZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jTextFieldIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeActionPerformed(evt);
            }
        });

        jTablePacijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePacijenti);

        jButtonPretraziPacijenta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonPretraziPacijenta.setText("pretraži");
        jButtonPretraziPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziPacijentaActionPerformed(evt);
            }
        });

        jButtonDetaljiPacijenta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonDetaljiPacijenta.setText("detalji pacijenta");
        jButtonDetaljiPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiPacijentaActionPerformed(evt);
            }
        });

        jTextFieldPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrezimeActionPerformed(evt);
            }
        });

        jLabel3.setText("Prezime:");

        jLabel4.setText("Državljanstvo:");

        jButtonZatvori.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonZatvori.setText("zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonDetaljiPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIme)
                                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDrzavljanstvo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addComponent(jButtonPretraziPacijenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxDrzavljanstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonPretraziPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDetaljiPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonZatvori)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeActionPerformed

    private void jButtonPretraziPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziPacijentaActionPerformed
        pretrazi();
    }//GEN-LAST:event_jButtonPretraziPacijentaActionPerformed

    private void jButtonDetaljiPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiPacijentaActionPerformed
        int row = jTablePacijenti.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Izaberi gosta iz tabele.");
            return;
        }
        
        TableModelPacijent tm = (TableModelPacijent) jTablePacijenti.getModel();
        Pacijent selektovan = tm.getPacijentAt(row);  

        FormaNoviPacijent dlg = new FormaNoviPacijent((java.awt.Frame) getParent(), true, selektovan);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            Pacijent pacijent = new Pacijent();
            if (!ime.isEmpty()) pacijent.setIme(ime);
            if (!prezime.isEmpty()) pacijent.setPrezime(prezime);
            if (drz != null) pacijent.setDrzavljanstvo(drz);

                ArrayList<Pacijent> lista = controller.KlijentController.getInstance().searchPacijent(pacijent);
                model.setData(lista);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje pacijenta.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetaljiPacijentaActionPerformed

    private void jTextFieldPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrezimeActionPerformed

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetaljiPacijenta;
    private javax.swing.JButton jButtonPretraziPacijenta;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JComboBox<Drzavljanstvo> jComboBoxDrzavljanstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacijenti;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void pretrazi() {
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            Pacijent pacijent = new Pacijent();
            if (!ime.isEmpty()) pacijent.setIme(ime);
            if (!prezime.isEmpty()) pacijent.setPrezime(prezime);
            if (drz != null) pacijent.setDrzavljanstvo(drz);

            ArrayList<Pacijent> lista = controller.KlijentController.getInstance().searchPacijent(pacijent);
            if(lista.isEmpty()) JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje pacijenta po zadatom kriterijumu.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this, "Sistem je nasao pacijente po zadatim kriterijumima", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            model.setData(lista);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje pacijenta.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void obrisiSelektovanog() {
        int row = jTablePacijenti.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Izaberi pacijenta za brisanje."); return; }

        Pacijent p = model.getPacijentAt(row);
        int potv = JOptionPane.showConfirmDialog(this,"Obrisati pacijenta " + p + "?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (potv != JOptionPane.YES_OPTION) return;

        try {
            KlijentController.getInstance().deletePacijent(p); 
            model.removeRow(row);                          
            JOptionPane.showMessageDialog(this, "Pacijent obrisan.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri brisanju: " + ex.getMessage());
        }
    }

    private void izmeniSelektovanog() {
        int row = jTablePacijenti.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Izaberi pacijenta iz tabele.");
            return;
        }

        Pacijent selektovan = model.getPacijentAt(row);
        if (selektovan == null) {
            JOptionPane.showMessageDialog(this, "Nije moguce procitati selektovanog pacijenta.");
            return;
        }

        FormaNoviPacijent dlg = new FormaNoviPacijent((java.awt.Frame) getParent(), true, selektovan);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);  

       try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            Pacijent pacijent = new Pacijent();
            if (!ime.isEmpty()) pacijent.setIme(ime);
            if (!prezime.isEmpty()) pacijent.setPrezime(prezime);
            if (drz != null) pacijent.setDrzavljanstvo(drz);

                ArrayList<Pacijent> lista = controller.KlijentController.getInstance().searchPacijent(pacijent);
                model.setData(lista);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje pacijenta.", "Greska", JOptionPane.ERROR_MESSAGE);
        } 
    }

    private void popuniDrzavljanstva() {
         try {
            java.util.ArrayList<domain.Drzavljanstvo> lista =
            controller.KlijentController.getInstance().getAllDrzavljanstvo();
            jComboBoxDrzavljanstvo.removeAllItems();
            jComboBoxDrzavljanstvo.addItem(null); 
            for (domain.Drzavljanstvo d : lista) jComboBoxDrzavljanstvo.addItem(d);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,"Greska pri ucitavanju drzavljanstava: " + ex.getMessage());
    }
    }
}
