/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.KlijentController;
import domain.Pacijent;
import domain.Lekar;
import domain.StavkaRacuna;
import domain.VrstaMedUsluge;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeli.TableModelStavkeRacuna;
import session.Session;

/**
 *
 * @author korisnk
 */
 class MainForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForma.class.getName());
    private static Lekar l;
    private TableModelStavkeRacuna tmStavke;
    private Lekar ulogovani;
    
    /**
     * Creates new form MainForma
     */
    public MainForma(Lekar l) {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        jTextFieldUkupno.setEnabled(false);
        jTextFieldDatum.setEnabled(false);
        jTextFieldCenaUsluge.setEnabled(false);
        
        this.l = l;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldDatum.setText(sdf.format(new Date()));
        jTextFieldDatum.setEditable(false);
        jLabelUlogovani.setText("Ulogovani lekar: " + l.getIme() + " " + l.getPrezime());
        setTitle("Poliklinika AsMedicus");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Racun"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke racuna"));
        
        tmStavke = new TableModelStavkeRacuna();
        jTableStavkeRacuna.setModel(tmStavke);
        
        
        jTextFieldCenaUsluge.setEditable(false);

        
        popuniUsluge();
        popuniPacijente();
        
        jButtonDodajStavku.addActionListener(e -> dodajStavku());
        jButtonObrisiStavku.addActionListener(e -> obrisiStavku());
        jButtonIzdajRacun.addActionListener(e -> izdajRacun());
        
      /*  jMenuItemDodajUslugu.addActionListener(e -> {
        FormaNovaVrstaUsluge d = new FormaNovaVrstaUsluge(this, true);
        d.setLocationRelativeTo(this);
        d.setVisible(true);
        popuniUsluge();
});*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPoliklinika = new javax.swing.JLabel();
        jLabelUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jTextFieldUkupno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxVrstaMedUsluge = new javax.swing.JComboBox<>();
        jTextFieldCenaUsluge = new javax.swing.JTextField();
        jTextFieldKolicina = new javax.swing.JTextField();
        jButtonObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeRacuna = new javax.swing.JTable();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonIzdajRacun = new javax.swing.JButton();
        jComboBoxPacijent = new javax.swing.JComboBox<>();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPacijent = new javax.swing.JMenu();
        jMenuItemDodajPacijenta = new javax.swing.JMenuItem();
        jMenuItemPretraziPacijenta = new javax.swing.JMenuItem();
        jMenuRacun = new javax.swing.JMenu();
        jMenuItempretraziRacun = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemDodajSpremu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPoliklinika.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelPoliklinika.setText("Poliklinika AsMedicus");

        jLabelUlogovani.setText("Ulogovani lekar:");

        jLabel3.setText("Pacijent:");

        jLabel4.setText("Datum:");

        jTextFieldUkupno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUkupnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Ukupno:");

        jLabel6.setText("Vrsta usluge:");

        jLabel7.setText("Cena usluge:");

        jLabel8.setText("Kolicina:");

        jComboBoxVrstaMedUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVrstaMedUslugeActionPerformed(evt);
            }
        });

        jTextFieldCenaUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCenaUslugeActionPerformed(evt);
            }
        });

        jTextFieldKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKolicinaActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonObrisiStavku.setText("obriši");

        jTableStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeRacuna);

        jButtonDodajStavku.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonDodajStavku.setText("dodaj");

        jButtonIzdajRacun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonIzdajRacun.setText("IZDAJ RACUN");
        jButtonIzdajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzdajRacunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxVrstaMedUsluge, 0, 451, Short.MAX_VALUE)
                            .addComponent(jTextFieldCenaUsluge)
                            .addComponent(jTextFieldKolicina)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonObrisiStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jButtonIzdajRacun, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVrstaMedUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodajStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonObrisiStavku)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCenaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonIzdajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxPacijent, 0, 229, Short.MAX_VALUE)
                    .addComponent(jTextFieldDatum)
                    .addComponent(jTextFieldUkupno))
                .addContainerGap(559, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuPacijent.setText("Pacijent");

        jMenuItemDodajPacijenta.setText("Dodaj pacijenta");
        jMenuItemDodajPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajPacijentaActionPerformed(evt);
            }
        });
        jMenuPacijent.add(jMenuItemDodajPacijenta);

        jMenuItemPretraziPacijenta.setText("Pretrazi pacijenta");
        jMenuItemPretraziPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziPacijentaActionPerformed(evt);
            }
        });
        jMenuPacijent.add(jMenuItemPretraziPacijenta);

        jMenuBar.add(jMenuPacijent);

        jMenuRacun.setText("Racun");

        jMenuItempretraziRacun.setText("Pretrazi racun");
        jMenuItempretraziRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItempretraziRacunActionPerformed(evt);
            }
        });
        jMenuRacun.add(jMenuItempretraziRacun);

        jMenuBar.add(jMenuRacun);

        jMenu4.setText("Strucna sprema");

        jMenuItemDodajSpremu.setText("Dodaj spremu");
        jMenuItemDodajSpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajSpremuActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDodajSpremu);

        jMenuBar.add(jMenu4);

        jMenu5.setText("Odjava");

        jMenuItemOdjaviSe.setText("Odjavi se");
        jMenuItemOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjaviSeActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemOdjaviSe);

        jMenuBar.add(jMenu5);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPoliklinika)
                .addGap(388, 388, 388))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPoliklinika, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUlogovani)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCenaUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCenaUslugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCenaUslugeActionPerformed

    private void jTextFieldKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKolicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKolicinaActionPerformed

    private void jMenuItemDodajPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajPacijentaActionPerformed
        FormaNoviPacijent pacijent = new FormaNoviPacijent(this, true);
        pacijent.setLocationRelativeTo(this);
        pacijent.setVisible(true);   
        popuniPacijente();  
    }//GEN-LAST:event_jMenuItemDodajPacijentaActionPerformed

    private void jComboBoxVrstaMedUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVrstaMedUslugeActionPerformed
        VrstaMedUsluge vu = (VrstaMedUsluge) jComboBoxVrstaMedUsluge.getSelectedItem();
        if (vu != null) jTextFieldCenaUsluge.setText(String.valueOf(vu.getCena()));
    }//GEN-LAST:event_jComboBoxVrstaMedUslugeActionPerformed

    private void jMenuItemDodajSpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajSpremuActionPerformed
        FormaDodajStrucnaSprema forma = new FormaDodajStrucnaSprema(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajSpremuActionPerformed

    private void jMenuItemPretraziPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziPacijentaActionPerformed
        
        FormaPretraziPacijent forma = new FormaPretraziPacijent(this, true);
        forma.setVisible(true);

    }//GEN-LAST:event_jMenuItemPretraziPacijentaActionPerformed

    private void jMenuItempretraziRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempretraziRacunActionPerformed
        
        FormaPretraziRacun forma = new FormaPretraziRacun(this, true);
        forma.setVisible(true);

    }//GEN-LAST:event_jMenuItempretraziRacunActionPerformed

    private void jMenuItemOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjaviSeActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                KlijentController.getInstance().logout(ulogovani);
                new LoginForma().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    }//GEN-LAST:event_jMenuItemOdjaviSeActionPerformed

    private void jButtonIzdajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzdajRacunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIzdajRacunActionPerformed

    private void jTextFieldUkupnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUkupnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUkupnoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonIzdajRacun;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JComboBox<Pacijent> jComboBoxPacijent;
    private javax.swing.JComboBox<VrstaMedUsluge> jComboBoxVrstaMedUsluge;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPoliklinika;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemDodajPacijenta;
    private javax.swing.JMenuItem jMenuItemDodajSpremu;
    private javax.swing.JMenuItem jMenuItemOdjaviSe;
    private javax.swing.JMenuItem jMenuItemPretraziPacijenta;
    private javax.swing.JMenuItem jMenuItempretraziRacun;
    private javax.swing.JMenu jMenuPacijent;
    private javax.swing.JMenu jMenuRacun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkeRacuna;
    private javax.swing.JTextField jTextFieldCenaUsluge;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldKolicina;
    private javax.swing.JTextField jTextFieldUkupno;
    // End of variables declaration//GEN-END:variables

    private void popuniUsluge() {
        try {
            ArrayList<VrstaMedUsluge> usluge = KlijentController.getInstance().getAllVrstaUsluge();
            jComboBoxVrstaMedUsluge.removeAllItems();
            for (VrstaMedUsluge v : usluge) {
                jComboBoxVrstaMedUsluge.addItem(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }

    private void popuniPacijente() {
        try {
            ArrayList<Pacijent> pacijenti = KlijentController.getInstance().getAllPacijent();
            jComboBoxPacijent.removeAllItems();
            for (Pacijent p : pacijenti) {
                jComboBoxPacijent.addItem(p);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void dodajStavku() {
        try {
            VrstaMedUsluge vu = (VrstaMedUsluge) jComboBoxVrstaMedUsluge.getSelectedItem();
            int kolicina = Integer.parseInt(jTextFieldKolicina.getText());
            double cena = vu.getCena(); 
            double iznos = cena * kolicina;

            StavkaRacuna sr = new StavkaRacuna();
            sr.setVrstaMedUsluge(vu);
            sr.setKolicina(kolicina);
            sr.setCenaUsluge(cena);
            sr.setIznos(iznos);

            tmStavke.dodajStavku(sr);
            
            jTextFieldUkupno.setText(String.valueOf(tmStavke.vratiUkupanIznos()));

            jTextFieldKolicina.setText("");
            jTextFieldCenaUsluge.setText(String.valueOf(cena));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Unesite ispravnu kolicinu!");
        }
    }

    private void obrisiStavku() {
        int row = jTableStavkeRacuna.getSelectedRow();
        if (row >= 0) {
        tmStavke.obrisiStavku(row);
        jTextFieldUkupno.setText(String.valueOf(tmStavke.vratiUkupanIznos()));
        } else {
        JOptionPane.showMessageDialog(this, "Morate izabrati stavku za brisanje!");
        }
    }

    private void izdajRacun() {
    try {
        Pacijent pacijent = (Pacijent) jComboBoxPacijent.getSelectedItem();
        if (pacijent == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati pacijenta.");
            return;
        }
        if (tmStavke.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti racun.", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date datum = sdf.parse(jTextFieldDatum.getText());

        double ukupno = tmStavke.vratiUkupanIznos();

        domain.Racun racun = new domain.Racun();
        racun.setDatumIzdavanja(datum);
        racun.setUkupniIznos(ukupno);
        racun.setLekar(l);           
        racun.setPacijent(pacijent);
        racun.setStavke(new ArrayList<>(tmStavke.getStavke()));

      
        KlijentController.getInstance().addRacun(racun);

        JOptionPane.showMessageDialog(this, "Sistem je zapamtio racun.");
        tmStavke.getStavke().clear();
        tmStavke.fireTableDataChanged();
        jTextFieldUkupno.setText("");
        jTextFieldKolicina.setText("");
        jTextFieldCenaUsluge.setText("");

        jTextFieldDatum.setText(sdf.format(new Date()));

       } catch (java.text.ParseException pe) {
           JOptionPane.showMessageDialog(this, "Datum nije u formatu dd/MM/yyyy.");
       } catch (Exception ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Greska pri izdavanju racuna!");
       }    
    }
}
